
version: "3.9"
services:
  redis:
    container_name: redisprobabilistic
    image: "redislabs/redismod"
    ports:
      - 6379:6379
    entrypoint:
      redis-server
        --loadmodule /usr/lib/redis/modules/redisbloom.so
        --appendonly yes
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure